sets.exported={
    main="Naegling",
    sub="Nusku Shield",
    range="Fomalhaut",
    ammo="Chrono Bullet",
    head="Nyame Helm",
    body="Malignance Tabard",
    hands="Malignance Gloves",
    legs={ name="Carmine Cuisses +1", augments={'Accuracy+20','Attack+12','"Dual Wield"+6',}},
    feet={ name="Lanun Bottes +3", augments={'Enhances "Wild Card" effect',}},
    neck={ name="Loricate Torque +1", augments={'Path: A',}},
    waist="Carrier's Sash",
    left_ear="Etiolation Earring",
    right_ear="Friomisi Earring",
    left_ring="Defending Ring",
    right_ring="Archon Ring",
    back={ name="Camulus's Mantle", augments={'AGI+16','Rng.Acc.+20 Rng.Atk.+20','Rng.Atk.+10','Weapon skill damage +10%','Damage taken-5%',}},
}